import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Provider } from "~/components/layout";
import { SiteHeader } from "~/components/site-header";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className=" grid place-items-center bg-[#3D3D3D] font-mono">
        <Provider>
          <SiteHeader />
          {children}
        </Provider>
      </body>
    </html>
  );
}
